### ISSUE TITLE
Best default vagrant distro?

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-Skeleton#65]
Maybe this won't make too much of a difference since we don't have any active 3.0 apps, but it could become a little more relevant as we start to upgrade existing deployed apps.

Can we do a quick informal pole of production distributions in use for our projects so we can pick a "default" (but obviously easily swappable) box for the new skeleton?

On my projects, we have Ubuntu 12.04 or 14.04 deployed everywhere that isn't a managed server we don't control (HostGator or Steadfast, for example.)

@ricog What's your most common production OS?

What makes the most sense for the skeleton to "recommend" as our "preferred" target?

**Comment by ricog** [comment]
I don't think we should count existing production OSs as we would be giving votes to CentOS and the like that I think we all agree aren't the best choice. Most of my projects OS choices pre-date my management of the project anyway.

Since it is fairly easy to swap out, we should instead base the default on the recommended distro, the one customers should use if possible. In my opinion this is Debian or Ubuntu. They are very similar, and I've been favoring Debian lately based on experience, recommendations, and concerns about the upcoming systemd split (Ubuntu probably won't give us a choice).

**Comment by alecho** [comment]
I'm going to agree with Rick on this, Debian is probably the best choice and it's fairly trivial to switch out the base box if something else is required for a specific project, especially going from Debian to Ubuntu.

**Comment by beporter** [comment]
Good enough for me. I prefer Ubuntu, but honestly I don't want to be **doing** anything in the VM all that much anyway. Closing.
